### ISSUE TITLE
Missing el_GR.dic

### ISSUE THREAD

**Issue by hubgit** [stevestavropoulos/elspell#1]
Since 77168092ab3adf6c8f43f326b0f66aadd6eb278b, the `myspell/el_GR.dic` file has been in the `.gitignore` file and missing from the repository. 

Would it be possible to restore `el_GR.dic` to the `myspell` folder, ideally the latest version ?

**Comment by stevestavropoulos** [comment]
The file is generated with the Makefile target included in the same commit. You just run `make myspell/el_GR.dic`. Look at the Makefile for details on what it actually runs.
